{% set name = "tempest-remap" %}
{% set version = "2.0.3" %}
{% set build = 8 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ClimateGlobalChange/tempestremap/archive/v{{ version }}.tar.gz
  sha256: b4578c2cb101ba091a10dc914e15ac968257f5db27ca78bc9fb5dbd70bce191f

build:
  skip: True  # [win]
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `tempest-remap * mpi_mpich_*` for mpich
  # `tempest-remap * mpi_*` for any mpi
  # `tempest-remap * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

  {% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libblas
    - liblapack
    # need to list hdf5 and libnetcdf twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - libblas
    - liblapack
    - hdf5 * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*

test:
  commands:
    - test -f ${PREFIX}/lib/libTempestRemap.a
    - test -f ${PREFIX}/lib/libTempestRemap${SHLIB_EXT}
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g

about:
  home: https://github.com/ClimateGlobalChange/tempestremap
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Remapping software for climate applications
  description: |
    TempestRemap is a conservative, consistent and monotone remapping package
    for arbitrary grid geometry with support for finite volumes and finite
    elements. There is still quite a bit of work to be done, but any feedback is
    appreciated on the software in its current form.

    If you choose to use this software in your work, please cite our papers:

    Paul A. Ullrich and Mark A. Taylor, 2015: Arbitrary-Order Conservative and
    Consistent Remapping and a Theory of Linear Maps: Part 1. Mon. Wea. Rev.,
    143, 2419–2440, doi: 10.1175/MWR-D-14-00343.1

    Paul A. Ullrich, Darshi Devendran and Hans Johansen, 2016: Arbitrary-Order
    Conservative and Consistent Remapping and a Theory of Linear Maps, Part 2.
    Mon. Weather Rev., 144, 1529-1549, doi: 10.1175/MWR-D-15-0301.1.
  doc_url: https://github.com/ClimateGlobalChange/tempestremap
  dev_url: https://github.com/ClimateGlobalChange/tempestremap

extra:
  recipe-maintainers:
    - jhkennedy
    - xylar
