travis:
  secure:
    BINSTAR_TOKEN: ABSr5VN0JmknqkGXm3D7MCkRlTQZmoo5pmJ5G4iAXo3MQ58angai1F2DDfJkJLXVHgn84lXzyh/nRkuvlXEeJLIIprUzSV8CyOU4kq0HnXNaaaDipjt+RMkad64kfcThMZgF/5b0DOqAJojAo+/fhchn7iyIKeFxKfdtE2CbMsP8AR/F8iXxlMRHZoNnIDeakiDdNdN/JBaKUGAD5Y6eP7KXRSnG8d5DJSSYnjpQ8jty+fbd1utdgo/eVIjDZ/MsaxXJnVCgZ3z4qU0P35HdMDsAWFgfuQAbUbuGPP6ziW2Z+7oOl1geSiSUMWACEBIUekOeIJ3eCjFDfHSyMbBl6o/iZzBpSJmV2nHKQWSQPpArYaJSdJZASHr1qtNAOL/s9CRcs3QXP6bzucMJKhYU/zkbKzCOFxra20ItlMy+XHVzWY8RkgU66NVoskV1dj27AsJ9wc2HpJqkzcHdFzmMiizZza3cbKhxEA/6FsMQKpWNbZwkUdiFd9Anu0hpBkYWoFaVCYqh2IclNj7TzA6ZbTzPGsWsDTfhZ5dxgJmse0o/99DEhFOz84gG8ko1PVZyKQxe1G9lyLjZh3zLqhD4Bcx/OfU39xsBsJdrfGcY/wXy3/chTdQa7t6NPsT0r/FiTW7t6VBMUX4OQAf4P7gD2fY4YAGzwNU8J7pXEUgX1NA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
